<?php
/**
 * Created by PhpStorm.
 * User: intern
 * Date: 2017/10/11
 * Time: 下午4:43
 */

namespace app\admin\controller;

use think\Controller;

class Category extends Controller
{

    private $obj;

    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->obj = model("Category");
    }

    public function index()
    {
        //获取parent_id   接收来自获取子栏目的id
        $parent_id = input('parent_id', 0, 'intval');

        //通过model获取分类数据
        $data = $this->obj->getFirstNormalCategories($parent_id);

        return $this->fetch('', [
            'categories' => $data
        ]);
    }

    /**
     *   修改状态的函数
     */
    public function status()
    {
        //get方法获取带过来的参数

        $data = input();

//        print_r($status);

        //校验

        $validate = validate('Category');


        $res = $validate->scene('status')->check($data);

        if (!$res) {

            $this->error($validate->getError());
        }

        //进入数据库切换状态

        $result = $this->obj->save(['status' => $data['status']], ['id' => $data['id']]);

        if (!$result) {
            $this->error('状态更新失败');
        }
        $this->success('状态更新成功');

    }
    /**
     *添加分类的方法,去页面
     */
    public function add()
    {

        //获取一级分类
        $category = $this->obj->getAllFirstNormalCategories();

        return $this->fetch('', ['categories' => $category]);
    }

    //保存分类的方法
    public function save()
    {
        //获取前端发送多来的表单数据(分类的添加)
        //判断请求类型

        if (!request()->isPost()) {
            $this->error('请求失败');
        }
//        print_r(input("post."));


        $data = input("post.");

        //校验数据

        $validate = validate('Category');

        $res = $validate->scene('add')->check($data);

        if (!$res) {
            $this->error($validate->getError());
        }

        //校验成功添加到数据库

        $result = $this->obj->save($data);

        if (!$result) {
            $this->error('新增失败');
        }

        $this->success('新增成功');

    }

    /**
     * 跳转到编辑的页面
     * @return mixed
     */
    public function edit()
    {

        $id = input('id', 0, 'intval');

        //根据id获取一行信息
        $category = $this->obj->get($id);

        $data = $this->obj->getAllFirstNormalCategories();

        return $this->fetch('', [
            'category' => $category,
            'categories' => $data
        ]);

    }

    public function update()
    {
        print_r(input());

        $data = input();

        $validate = validate('Category');

        $res = $validate->scene('update')->check($data);


        if (!$res) {
            $this->error($validate->getError());
        }


        //修改数据
        $result = $this->obj->save(['name' => $data['name'], 'parent_id' => $data['parent_id']], ['id' => $data['id']]);

        if (!$result) {
            $this->error('更新失败');
        }

        $this->success('更新成功');

    }

    public function listorder()
    {
//        print_r(input('post.'));


        $data = input('post.');

        $validate = validate('Category');

        $res = $validate->scene('listorder')->check($data);

        if (!$res){
            $this->error($validate->getError());
        }

        //第一个参数是数据,第二个参数是条件
        $res = $this->obj->save(['listorder'=>$data['listorder']],['id'=>$data['id']]);


        //result 框架的方法,返回ajax的数据

        if (!$res){
            $this->result($_SERVER['HTTP_REFERER'],0,'error');
        }

        $this->result($_SERVER['HTTP_REFERER'],1,'success');
    }

    /**
     * 测试图片的方法
     */
    public function test(){
        $res = \Map::staticImage('北海市铁山港区南康中学');
        return $res;
    }

}

